In [1]:
import tensorflow as tf

C:\Users\ruma\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
hello = tf.constant("hello world")

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(hello))

b'hello world'


In [5]:
print(tf.__version__)

1.9.0


In [6]:
hello = tf.constant("Hello")

In [7]:
world = tf.constant("World")

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'HelloWorld'


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [17]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [19]:
result

30

In [20]:
const = tf.constant(10)

In [21]:
fill_mat = tf.fill((4,4),10)

In [22]:
myzeros = tf.zeros((4,4))

In [23]:
myones = tf.ones((4,4))

In [24]:
myrandn = tf.random_normal((4,4), mean=0,stddev=1.0)

In [25]:
myrandu = tf.random_uniform((4,4),minval=0, maxval=1)

In [26]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [27]:
sess = tf.InteractiveSession()

In [29]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.17800853 -1.3590829   1.0429659   1.0801787 ]
 [-0.29098698 -0.4222177  -0.37488687 -0.8999259 ]
 [ 0.25962314 -0.47748396 -0.8998091  -0.14929272]
 [ 0.25792757  0.16334601 -1.0982211  -1.3348045 ]]


[[0.5256667  0.3548324  0.90567946 0.49209738]
 [0.9260113  0.84916854 0.9814906  0.07993543]
 [0.5131036  0.41233218 0.32754683 0.80670166]
 [0.15920556 0.70335484 0.9650346  0.04758751]]




In [34]:
a = tf.constant([[1,2],[3,4]])
    

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [36]:
b = tf.constant([[10],[20]])

In [37]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [38]:
result = tf.matmul(a,b)

In [39]:
sess.run(result)

array([[ 50],
       [110]])

In [40]:
result.eval()

array([[ 50],
       [110]])

In [41]:
n1 = tf.constant(1)

In [42]:
n2 = tf.constant(2)

In [43]:
n3 = n1+n2

In [44]:
with tf.Session() as sess:
    result = sess.run(n3)

In [45]:
print(result)

3


In [46]:
print(tf.get_default_graph())

In [47]:
g = tf.Graph()

In [48]:
print(g)

In [49]:
graph_one = tf.get_default_graph()

In [50]:
print(graph_one)

In [51]:
graph_two = tf.Graph()

In [52]:
print(graph_two)

In [53]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [54]:
print(graph_two is tf.get_default_graph())

False


In [56]:
my_tensor = tf.random_uniform((4,4),0,1)

In [57]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [58]:
my_var = tf.Variable(initial_value = my_tensor)

In [59]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [60]:
init = tf.global_variables_initializer()

In [61]:
sess.run(init)

In [62]:
sess.run(my_var)

array([[0.331092  , 0.9346217 , 0.7520404 , 0.5168297 ],
       [0.96335065, 0.40473008, 0.47927117, 0.39571786],
       [0.9254625 , 0.36925745, 0.39372337, 0.32328463],
       [0.43029642, 0.6152282 , 0.11810625, 0.9384203 ]], dtype=float32)

In [63]:
ph = tf.placeholder(tf.float32, shape = (None,4))